//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitchhikerGuide.Data.PublisherClient.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Planet", Namespace="http://schemas.datacontract.org/2004/07/PublisherService.Service")]
    [System.SerializableAttribute()]
    public partial class Planet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasAtmosphereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkyColourField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAtmosphere {
            get {
                return this.HasAtmosphereField;
            }
            set {
                if ((this.HasAtmosphereField.Equals(value) != true)) {
                    this.HasAtmosphereField = value;
                    this.RaisePropertyChanged("HasAtmosphere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkyColour {
            get {
                return this.SkyColourField;
            }
            set {
                if ((object.ReferenceEquals(this.SkyColourField, value) != true)) {
                    this.SkyColourField = value;
                    this.RaisePropertyChanged("SkyColour");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://services.github.com/TimothyK/HitchhikerGuide/Publisher", ConfigurationName="Services.IPublisher")]
    public interface IPublisher {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/UpdateP" +
            "lanet", ReplyAction="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/UpdateP" +
            "lanetResponse")]
        void UpdatePlanet(System.Guid requestId, string author, HitchhikerGuide.Data.PublisherClient.Services.Planet planet);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/GetPlan" +
            "ets", ReplyAction="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/GetPlan" +
            "etsResponse")]
        HitchhikerGuide.Data.PublisherClient.Services.Planet[] GetPlanets(System.Guid requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/DeleteP" +
            "lanet", ReplyAction="https://services.github.com/TimothyK/HitchhikerGuide/Publisher/IPublisher/DeleteP" +
            "lanetResponse")]
        void DeletePlanet(System.Guid requestId, HitchhikerGuide.Data.PublisherClient.Services.Planet planet);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublisherChannel : HitchhikerGuide.Data.PublisherClient.Services.IPublisher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublisherClient : System.ServiceModel.ClientBase<HitchhikerGuide.Data.PublisherClient.Services.IPublisher>, HitchhikerGuide.Data.PublisherClient.Services.IPublisher {
        
        public PublisherClient() {
        }
        
        public PublisherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublisherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublisherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdatePlanet(System.Guid requestId, string author, HitchhikerGuide.Data.PublisherClient.Services.Planet planet) {
            base.Channel.UpdatePlanet(requestId, author, planet);
        }
        
        public HitchhikerGuide.Data.PublisherClient.Services.Planet[] GetPlanets(System.Guid requestId) {
            return base.Channel.GetPlanets(requestId);
        }
        
        public void DeletePlanet(System.Guid requestId, HitchhikerGuide.Data.PublisherClient.Services.Planet planet) {
            base.Channel.DeletePlanet(requestId, planet);
        }
    }
}
